// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxbcshbuvmromjefsqyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4YmNzaGJ1dm1yb21qZWZzcXlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NzUwMDMsImV4cCI6MjA2MjM1MTAwM30.fBym_mthNPqtr9tF92gUTr3RKBVwsTDILbOu3mK74hA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);